-- 智慧医养平台数据库修复脚本
-- 创建数据库
CREATE DATABASE IF NOT EXISTS smartcare_cloud DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE smartcare_cloud;
-- 删除旧表（如果存在）
DROP TABLE IF EXISTS elderly;
-- 重新创建老人档案表（与后端代码匹配）
CREATE TABLE elderly (
  id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  name VARCHAR(50) NOT NULL COMMENT '姓名',
  gender TINYINT(1) NOT NULL COMMENT '性别 (1-男, 0-女)',
  id_card VARCHAR(18) NOT NULL COMMENT '身份证号',
  birth_date DATE NULL COMMENT '出生日期',
  age INT(3) NULL COMMENT '年龄',
  phone VARCHAR(20) NULL COMMENT '联系电话',
  address VARCHAR(255) NULL COMMENT '家庭地址',
  emergency_contact_name VARCHAR(50) NULL COMMENT '紧急联系人姓名',
  emergency_contact_phone VARCHAR(20) NULL COMMENT '紧急联系人电话',
  health_status VARCHAR(20) NOT NULL DEFAULT 'HEALTHY' COMMENT '健康状况 (HEALTHY-健康, SUBHEALTH-亚健康, SICK-疾病, SERIOUS-重病, DANGER-危险, WARNING-预警)',
  care_level TINYINT(1) NOT NULL DEFAULT 1 COMMENT '照护等级 (1-自理, 2-半自理, 3-不能自理)',
  insurance_type VARCHAR(50) NULL COMMENT '医保类型',
  medical_history TEXT NULL COMMENT '既往病史',
  allergy_history TEXT NULL COMMENT '过敏史',
  family_doctor_id BIGINT(20) NULL COMMENT '家庭医生ID',
  status TINYINT(1) NOT NULL DEFAULT 1 COMMENT '档案状态 (1-正常, 0-停用)',
  remarks TEXT NULL COMMENT '备注',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  create_by VARCHAR(50) NULL COMMENT '创建者',
  update_by VARCHAR(50) NULL COMMENT '更新者',
  is_deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除 (1-已删除, 0-未删除)',
  PRIMARY KEY (id),
  UNIQUE KEY uk_id_card (id_card),
  KEY idx_name (name),
  KEY idx_phone (phone),
  KEY idx_health_status (health_status),
  KEY idx_create_time (create_time)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '老人档案表';
-- 插入测试数据
INSERT INTO elderly (
    name,
    gender,
    id_card,
    birth_date,
    age,
    phone,
    address,
    emergency_contact_name,
    emergency_contact_phone,
    health_status,
    care_level,
    insurance_type,
    medical_history,
    create_by
  )
VALUES (
    'Zhang Ming',
    1,
    '110101195001011234',
    '1950-01-01',
    74,
    '13800138001',
    'Beijing Chaoyang District',
    'Zhang XiaoMing',
    '13900139001',
    'HEALTHY',
    1,
    'Employee Insurance',
    'Hypertension for 5 years',
    'system'
  ),
  (
    'Li Hua',
    0,
    '110101194512152345',
    '1945-12-15',
    79,
    '13800138002',
    'Beijing Haidian District',
    'Li XiaoHua',
    '13900139002',
    'SUBHEALTH',
    2,
    'Resident Insurance',
    'Diabetes, Heart Disease',
    'system'
  ),
  (
    'Wang Fang',
    0,
    '110101195203203456',
    '1952-03-20',
    72,
    '13800138003',
    'Beijing Xicheng District',
    'Wang XiaoFang',
    '13900139003',
    'WARNING',
    1,
    'Employee Insurance',
    'Osteoporosis',
    'system'
  ),
  (
    'Liu Qiang',
    1,
    '110101194810104567',
    '1948-10-10',
    76,
    '13800138004',
    'Beijing Dongcheng District',
    'Liu XiaoQiang',
    '13900139004',
    'DANGER',
    3,
    'Resident Insurance',
    'Stroke, Hypertension, Diabetes',
    'system'
  ),
  (
    'Chen Jing',
    0,
    '110101195506066789',
    '1955-06-06',
    69,
    '13800138005',
    'Beijing Fengtai District',
    'Chen XiaoJing',
    '13900139005',
    'SICK',
    2,
    'Employee Insurance',
    'Asthma',
    'system'
  );
-- 创建医生信息表
CREATE TABLE IF NOT EXISTS doctor (
  id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  name VARCHAR(50) NOT NULL COMMENT '医生姓名',
  gender TINYINT(1) NOT NULL COMMENT '性别 (1-男, 0-女)',
  phone VARCHAR(20) NOT NULL COMMENT '联系电话',
  email VARCHAR(100) NULL COMMENT '邮箱地址',
  department VARCHAR(100) NOT NULL COMMENT '科室',
  title VARCHAR(50) NOT NULL COMMENT '职称',
  speciality VARCHAR(200) NULL COMMENT '专业特长',
  experience_years INT(2) NULL COMMENT '从业年限',
  license_number VARCHAR(50) NOT NULL COMMENT '执业证书号',
  introduction TEXT NULL COMMENT '个人简介',
  status TINYINT(1) NOT NULL DEFAULT 1 COMMENT '状态 (1-正常, 0-停用)',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  create_by VARCHAR(50) NULL COMMENT '创建者',
  update_by VARCHAR(50) NULL COMMENT '更新者',
  is_deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除 (1-已删除, 0-未删除)',
  PRIMARY KEY (id),
  UNIQUE KEY uk_license_number (license_number),
  KEY idx_name (name),
  KEY idx_department (department),
  KEY idx_phone (phone)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '医生信息表';
-- 插入医生测试数据
INSERT INTO doctor (
    name,
    gender,
    phone,
    email,
    department,
    title,
    speciality,
    experience_years,
    license_number,
    introduction,
    create_by
  )
VALUES (
    'Dr. Liu',
    1,
    '13700137001',
    'liudoctor@hospital.com',
    'Internal Medicine',
    'Attending Physician',
    'Cardiovascular Disease',
    15,
    'MD001234567',
    'Cardiovascular specialist with 15 years experience',
    'system'
  ),
  (
    'Dr. Wang',
    0,
    '13700137002',
    'wangdoctor@hospital.com',
    'Endocrinology',
    'Associate Chief Physician',
    'Diabetes Treatment',
    20,
    'MD001234568',
    'Diabetes expert with 20 years experience',
    'system'
  ),
  (
    'Dr. Zhang',
    1,
    '13700137003',
    'zhangdoctor@hospital.com',
    'Neurology',
    'Chief Physician',
    'Cerebrovascular Disease',
    25,
    'MD001234569',
    'Neurology expert and cerebrovascular disease authority',
    'system'
  );