-- 医生表修复脚本
-- 删除已存在的医生表（如果存在）
DROP TABLE IF EXISTS `t_doctor`;

-- 重新创建医生信息表
CREATE TABLE `t_doctor` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `employee_number` VARCHAR(50) NOT NULL COMMENT '医生工号',
  `name` VARCHAR(50) NOT NULL COMMENT '医生姓名',
  `gender` VARCHAR(10) NOT NULL COMMENT '性别',
  `age` INT(3) NULL COMMENT '年龄',
  `phone` VARCHAR(20) NOT NULL COMMENT '联系电话',
  `email` VARCHAR(100) NULL COMMENT '邮箱地址',
  `department` VARCHAR(100) NOT NULL COMMENT '科室',
  `title` VARCHAR(50) NOT NULL COMMENT '职称',
  `specialization` TEXT NULL COMMENT '专业特长',
  `experience_years` INT(2) NULL COMMENT '从业年限',
  `hospital_id` BIGINT(20) NULL COMMENT '所属医院ID',
  `hospital_name` VARCHAR(100) NULL COMMENT '所属医院名称',
  `license_number` VARCHAR(50) NULL COMMENT '执业证书号',
  `status` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '状态 (1-在职, 0-离职)',
  `avatar` VARCHAR(255) NULL COMMENT '头像URL',
  `remark` TEXT NULL COMMENT '备注',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_employee_number` (`employee_number`),
  KEY `idx_name` (`name`),
  KEY `idx_department` (`department`),
  KEY `idx_title` (`title`),
  KEY `idx_phone` (`phone`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '医生信息表';

-- 插入示例数据
INSERT INTO `t_doctor` (
    `employee_number`,
    `name`,
    `gender`,
    `age`,
    `phone`,
    `email`,
    `department`,
    `title`,
    `specialization`,
    `experience_years`,
    `hospital_name`
) VALUES 
(
    'D001',
    '刘医生',
    '男',
    45,
    '13700137001',
    'dr.liu@hospital.com',
    '内科',
    '主任医师',
    '心血管疾病诊疗',
    20,
    '北京市第一人民医院'
),
(
    'D002',
    '张医生',
    '女',
    38,
    '13700137002',
    'dr.zhang@hospital.com',
    '妇科',
    '副主任医师',
    '妇科常见病诊疗',
    15,
    '北京市第一人民医院'
),
(
    'D003',
    '王医生',
    '男',
    42,
    '13700137003',
    'dr.wang@hospital.com',
    '外科',
    '主治医师',
    '普外科手术',
    18,
    '北京市第二人民医院'
),
(
    'D004',
    '李医生',
    '女',
    35,
    '13700137004',
    'dr.li@hospital.com',
    '儿科',
    '主治医师',
    '儿科常见病',
    12,
    '北京市儿童医院'
),
(
    'D005',
    '陈医生',
    '男',
    50,
    '13700137005',
    'dr.chen@hospital.com',
    '骨科',
    '主任医师',
    '骨科创伤与修复',
    25,
    '北京市骨科医院'
),
(
    'D006',
    '赵医生',
    '女',
    43,
    '13700137006',
    'dr.zhao@hospital.com',
    '皮肤科',
    '主治医师',
    '皮肤病诊疗',
    16,
    '北京市皮肤病医院'
),
(
    'D007',
    '周医生',
    '男',
    39,
    '13700137007',
    'dr.zhou@hospital.com',
    '眼科',
    '副主任医师',
    '眼科手术',
    14,
    '北京市眼科医院'
),
(
    'D008',
    '吴医生',
    '女',
    36,
    '13700137008',
    'dr.wu@hospital.com',
    '耳鼻喉科',
    '主治医师',
    '耳鼻喉疾病',
    11,
    '北京市五官科医院'
),
(
    'D009',
    '郑医生',
    '男',
    52,
    '13700137009',
    'dr.zheng@hospital.com',
    '神经科',
    '主任医师',
    '神经系统疾病',
    28,
    '北京市神经病医院'
),
(
    'D010',
    '孙医生',
    '女',
    41,
    '13700137010',
    'dr.sun@hospital.com',
    '心血管科',
    '副主任医师',
    '心血管介入治疗',
    17,
    '北京市心血管医院'
);
