-- 智慧医养老人档案管理表结构优化
-- 添加老人档案扩展字段
ALTER TABLE elderly
ADD COLUMN emergency_contact VARCHAR(100) COMMENT '紧急联系人姓名',
  ADD COLUMN emergency_phone VARCHAR(20) COMMENT '紧急联系人电话',
  ADD COLUMN care_level TINYINT(1) DEFAULT 1 COMMENT '照护等级:1-自理,2-半自理,3-不能自理',
  ADD COLUMN family_doctor_id BIGINT COMMENT '家庭医生ID',
  ADD COLUMN status TINYINT(1) DEFAULT 1 COMMENT '档案状态:1-正常,0-停用',
  ADD COLUMN blood_type VARCHAR(5) COMMENT '血型:A,B,AB,O',
  ADD COLUMN height DECIMAL(5, 2) COMMENT '身高(cm)',
  ADD COLUMN weight DECIMAL(5, 2) COMMENT '体重(kg)',
  ADD COLUMN medical_history TEXT COMMENT '既往病史',
  ADD COLUMN allergy_history TEXT COMMENT '过敏史',
  ADD COLUMN medication_history TEXT COMMENT '用药史',
  ADD COLUMN family_medical_history TEXT COMMENT '家族病史',
  ADD COLUMN adl_score INT DEFAULT 100 COMMENT 'ADL日常生活能力评分',
  ADD COLUMN mmse_score INT COMMENT 'MMSE认知功能评分',
  ADD COLUMN special_needs TEXT COMMENT '特殊照护需求',
  ADD COLUMN diet_requirements TEXT COMMENT '饮食要求',
  ADD COLUMN mobility_status VARCHAR(20) DEFAULT 'NORMAL' COMMENT '行动能力:NORMAL-正常,ASSISTED-辅助,WHEELCHAIR-轮椅,BEDRIDDEN-卧床',
  ADD COLUMN room_number VARCHAR(20) COMMENT '房间号',
  ADD COLUMN entry_date DATE COMMENT '入住日期',
  ADD COLUMN guardian_name VARCHAR(50) COMMENT '监护人姓名',
  ADD COLUMN guardian_phone VARCHAR(20) COMMENT '监护人电话',
  ADD COLUMN guardian_relation VARCHAR(20) COMMENT '监护人关系',
  ADD COLUMN avatar_url VARCHAR(255) COMMENT '头像URL',
  ADD COLUMN remark TEXT COMMENT '备注信息';
-- 创建老人健康记录表
CREATE TABLE IF NOT EXISTS elderly_health_record (
  id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '记录ID',
  elderly_id BIGINT NOT NULL COMMENT '老人ID',
  record_date DATE NOT NULL COMMENT '记录日期',
  record_type VARCHAR(20) NOT NULL COMMENT '记录类型:CHECKUP-体检,VITAL-生命体征,MEDICATION-用药,INCIDENT-事件',
  doctor_id BIGINT COMMENT '医生ID',
  systolic_pressure INT COMMENT '收缩压',
  diastolic_pressure INT COMMENT '舒张压',
  heart_rate INT COMMENT '心率',
  body_temperature DECIMAL(4, 1) COMMENT '体温',
  blood_glucose DECIMAL(5, 2) COMMENT '血糖',
  weight DECIMAL(5, 2) COMMENT '体重',
  height DECIMAL(5, 2) COMMENT '身高',
  bmi DECIMAL(4, 1) COMMENT 'BMI指数',
  symptoms TEXT COMMENT '症状描述',
  diagnosis TEXT COMMENT '诊断',
  treatment TEXT COMMENT '治疗方案',
  medication TEXT COMMENT '用药情况',
  doctor_advice TEXT COMMENT '医嘱',
  next_checkup_date DATE COMMENT '下次检查日期',
  is_abnormal TINYINT(1) DEFAULT 0 COMMENT '是否异常:0-正常,1-异常',
  urgency_level TINYINT(1) DEFAULT 1 COMMENT '紧急程度:1-普通,2-注意,3-紧急',
  created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  INDEX idx_elderly_id (elderly_id),
  INDEX idx_record_date (record_date),
  INDEX idx_record_type (record_type)
) COMMENT = '老人健康记录表';
-- 创建照护评估记录表
CREATE TABLE IF NOT EXISTS elderly_care_assessment (
  id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '评估ID',
  elderly_id BIGINT NOT NULL COMMENT '老人ID',
  assessment_date DATE NOT NULL COMMENT '评估日期',
  assessor_id BIGINT COMMENT '评估员ID',
  assessor_name VARCHAR(50) COMMENT '评估员姓名',
  adl_score INT DEFAULT 0 COMMENT 'ADL评分(0-100)',
  iadl_score INT DEFAULT 0 COMMENT 'IADL评分(0-100)',
  mmse_score INT DEFAULT 0 COMMENT 'MMSE认知评分(0-30)',
  depression_score INT DEFAULT 0 COMMENT '抑郁评分',
  mobility_score INT DEFAULT 0 COMMENT '活动能力评分',
  social_score INT DEFAULT 0 COMMENT '社交能力评分',
  care_level TINYINT(1) NOT NULL COMMENT '照护等级:1-自理,2-半自理,3-不能自理',
  special_needs TEXT COMMENT '特殊照护需求',
  diet_requirements TEXT COMMENT '饮食要求',
  medication_management TEXT COMMENT '用药管理要求',
  safety_considerations TEXT COMMENT '安全注意事项',
  recommended_services TEXT COMMENT '推荐服务项目',
  next_assessment_date DATE COMMENT '下次评估日期',
  assessment_result TEXT COMMENT '评估结论',
  remark TEXT COMMENT '备注',
  created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  INDEX idx_elderly_id (elderly_id),
  INDEX idx_assessment_date (assessment_date),
  INDEX idx_care_level (care_level)
) COMMENT = '老人照护评估记录表';
-- 创建老人服务记录表
CREATE TABLE IF NOT EXISTS elderly_service_record (
  id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '服务记录ID',
  elderly_id BIGINT NOT NULL COMMENT '老人ID',
  service_date DATE NOT NULL COMMENT '服务日期',
  service_type VARCHAR(50) NOT NULL COMMENT '服务类型',
  service_provider_id BIGINT COMMENT '服务提供者ID',
  service_provider_name VARCHAR(50) COMMENT '服务提供者姓名',
  service_content TEXT COMMENT '服务内容',
  service_duration INT COMMENT '服务时长(分钟)',
  service_quality_score TINYINT(1) COMMENT '服务质量评分(1-5)',
  elderly_satisfaction TINYINT(1) COMMENT '老人满意度(1-5)',
  service_cost DECIMAL(10, 2) COMMENT '服务费用',
  service_status VARCHAR(20) DEFAULT 'COMPLETED' COMMENT '服务状态:PENDING-待服务,IN_PROGRESS-进行中,COMPLETED-已完成,CANCELLED-已取消',
  feedback TEXT COMMENT '服务反馈',
  remark TEXT COMMENT '备注',
  created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  INDEX idx_elderly_id (elderly_id),
  INDEX idx_service_date (service_date),
  INDEX idx_service_type (service_type),
  INDEX idx_service_status (service_status)
) COMMENT = '老人服务记录表';