server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: smartcare-cloud-backend

  profiles:
    active: dev

  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/smartcare_cloud?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&autoReconnect=true&rewriteBatchedStatements=true
      username: root
      password: 123456
      # 连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 监控统计拦截的filters
      filters: stat,wall,slf4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  # Redis配置（暂未启用，待后续性能优化时开启缓存功能）
  # redis:
  #   host: localhost
  #   port: 6379
  #   password:
  #   database: 0
  #   timeout: 10000ms
  #   jedis:
  #     pool:
  #       max-active: 8
  #       max-wait: -1ms
  #       max-idle: 8
  #       min-idle: 0

  # Jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

# MyBatis Plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  # 开启驼峰下划线互转
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# PageHelper分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# 日志配置
logging:
  level:
    com.smartcare.cloud: debug
    org.springframework.security: debug
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n'

# Swagger配置
springfox:
  documentation:
    swagger-ui:
      enabled: true
    open-api:
      v3:
        path: /v3/api-docs

# JWT配置
jwt:
  # 安全密钥 - 至少64字节(512位)以满足HS512算法要求
  secret: smartcare-cloud-jwt-secret-key-2024-secure-enough-for-hs512-algorithm-minimum-64-bytes-required
  # Token过期时间(秒) - 默认2小时
  expiration: 7200
  # 签发者
  issuer: smartcare-cloud
  # 刷新Token过期时间(秒) - 默认7天
  refresh-expiration: 604800

---
# 开发环境配置
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    druid:
      username: root
      password: 123456
  redis:
    password:
logging:
  level:
    root: info
    com.smartcare.cloud: debug

---
# 测试环境配置
spring:
  config:
    activate:
      on-profile: test
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/smartcare_cloud_test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&autoReconnect=true&rewriteBatchedStatements=true
      username: root
      password: 123456

---
# 生产环境配置
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/smartcare_cloud_prod?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&autoReconnect=true&rewriteBatchedStatements=true
      username: ${DB_USERNAME:root}
      password: ${DB_PASSWORD:123456}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
logging:
  level:
    root: warn
    com.smartcare.cloud: info
